name: Deebo CI (macOS Only)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  basic-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install uv and uvx
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: |
          npm install
          cd ci/mcp-client
          npm install

      - name: Build Deebo and MCP client
        shell: bash
        run: |
          npm run build
          cd ci/mcp-client
          npm run build

      - name: Clone fixture repo
        shell: bash
        run: |
          rm -rf task-manager-fixture
          git clone https://github.com/snagasuri/task-manager.git task-manager-fixture

      - name: Run CI client
        shell: bash
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          CI_LLM_MODEL: deepseek/deepseek-chat
        run: |
          # arguments: <path to deebo build> <path to fixture>
          node ci/mcp-client/build/index.js \
            build/index.js \
            $(pwd)/task-manager-fixture

      - name: Upload logs and memory-bank
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-macos
          path: |
            memory-bank/
            deebo_server.log
            client_output.log