name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Build and Test
        run: |
          npm install
          npm run build
          npm test
    
      - name: Debug file handles
        run: |
          echo 'Checking file existence and accessibility:'
          ls -l mother.log scenario.logs output.logs
          echo 'Checking open file handles:'
          lsof | grep -E 'mother.log|scenario.logs|output.logs'

      - name: Upload mother log
        uses: actions/upload-artifact@v3
        with:
          name: mother-log
          path: mother.log
          retention-days: 7
          if-no-files-found: error

      - name: Upload scenario logs
        uses: actions/upload-artifact@v3
        with:
          name: scenario-logs
          path: scenario.logs
          retention-days: 7
          if-no-files-found: error

      - name: Upload output logs
        uses: actions/upload-artifact@v3
        with:
          name: output-logs
          path: output.logs
          retention-days: 7
          if-no-files-found: error
