name: Deebo Basic CI

on:
  push:
    branches:
      - master
      - fix-ci-env-vars
  pull_request:
    branches:
      - master
      - fix-ci-env-vars

jobs:
  basic-test:
    runs-on: macos-latest
    timeout-minutes: 25
    env:
      NODE_ENV: development
      USE_MEMORY_BANK: "true"
      MOTHER_HOST: openrouter
      MOTHER_MODEL: anthropic/claude-3.5-sonnet
      SCENARIO_HOST: openrouter
      SCENARIO_MODEL: deepseek/deepseek-chat
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout Deebo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install ripgrep (macOS)
        run: |
          brew install ripgrep
          echo "RIPGREP_PATH=$(which rg)" >> $GITHUB_ENV

      - name: Install uv (macOS)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Determine tool paths
        id: tool_paths
        shell: bash
        run: |
          find_command() {
            local cmd=$1
            local where_cmd="which"
            local found_path=$($where_cmd $cmd 2>/dev/null | head -n 1)
            echo "$found_path"
          }
          NPX_PATH=$(find_command npx)
          UVX_PATH=$(find_command uvx)
          NPM_BIN=$(dirname "$NPX_PATH")
          if [[ -z "$NPX_PATH" || -z "$UVX_PATH" ]]; then
            echo "Error: Could not find npx or uvx path."
            exit 1
          fi
          NPX_PATH_ESC=$(echo "$NPX_PATH" | sed 's/\\/\\\\/g')
          UVX_PATH_ESC=$(echo "$UVX_PATH" | sed 's/\\/\\\\/g')
          NPM_BIN_ESC=$(echo "$NPM_BIN" | sed 's/\\/\\\\/g')
          echo "DEEBO_NPX_PATH=${NPX_PATH_ESC}" >> $GITHUB_ENV
          echo "DEEBO_UVX_PATH=${UVX_PATH_ESC}" >> $GITHUB_ENV
          echo "DEEBO_NPM_BIN=${NPM_BIN_ESC}" >> $GITHUB_ENV

      - name: Install Deebo dependencies
        env:
          RIPGREP_PATH: ${{ env.RIPGREP_PATH }}
          NPM_CONFIG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//api.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          npm install --loglevel error --no-optional

      - name: Build Deebo
        run: |
          npm run build

      - name: Build minimal MCP client
        working-directory: ci/mcp-client
        env:
          RIPGREP_PATH: ${{ env.RIPGREP_PATH }}
          NPM_CONFIG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//api.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          npm install --loglevel error --no-optional
          npm run build

      - name: Clone task manager fixture repo
        run: |
          rm -rf task-manager-fixture
          git clone https://github.com/snagasuri/task-manager.git task-manager-fixture

      - name: Check OpenRouter API key status
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          echo "Checking API key status..."
          if curl -fsS -G "https://openrouter.ai/api/v1/auth/key" \
             -H "Authorization: Bearer $OPENROUTER_API_KEY" \
             -o key_status.json && \
             jq -e '.data.label' key_status.json > /dev/null; then
            echo "API key is valid."
          else
            echo "Error: API key is invalid."
            cat key_status.json || echo "No response file."
            exit 1
          fi

      - name: Run Deebo server and test client (direct tool calls)
        id: deebo_run
        shell: bash
        run: |
          set -e
          DEEBO_BUILD=$(pwd)/build/index.js
          CLIENT_BUILD=$(pwd)/ci/mcp-client/build/index.js
          FIXTURE=$(pwd)/task-manager-fixture
          rm -rf memory-bank

          # start Deebo server in background with single-session mode
          echo "Launching Deebo server..."
          node "$DEEBO_BUILD" --once &
          SERVER_PID=$!
          echo "Deebo server PID: $SERVER_PID"
          sleep 2

          # run MCP client
          echo "Running client against server..."
          node "$CLIENT_BUILD" "$DEEBO_BUILD" "$FIXTURE" | tee client_output.log
          CLIENT_EXIT=${PIPESTATUS[0]}
          if [[ $CLIENT_EXIT -ne 0 ]]; then
            echo "Client failed with code $CLIENT_EXIT"
            kill $SERVER_PID || true
            exit $CLIENT_EXIT
          fi

          # shut down server
          echo "Stopping Deebo server..."
          kill $SERVER_PID
          wait $SERVER_PID 2>/dev/null || true

          # extract IDs and assert
          SESSION_ID=$(grep 'FINAL_SESSION_ID_MARKER:' client_output.log | cut -d':' -f2)
          SESSION_ID=${SESSION_ID:-$(grep '✅ Started session:' client_output.log | sed 's/✅ Started session: //')}
          PROJECT_ID=$(node -p "require('./build/util/sanitize.js').getProjectId('$FIXTURE')")

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "SESSION_ID=$SESSION_ID" >> $GITHUB_ENV

      - name: Debug logs folder
        run: |
          echo "PROJECT_ID=$PROJECT_ID SESSION_ID=$SESSION_ID"
          ls -R memory-bank/${PROJECT_ID}/sessions/${SESSION_ID}

      - name: Upload mother log
        uses: actions/upload-artifact@v4
        with:
          name: mother-log
          path: memory-bank/${{ env.PROJECT_ID }}/sessions/${{ env.SESSION_ID }}/logs/mother.log
          if-no-files-found: error
          retention-days: 7
